en:
  languageName: 'English'
  languageCode: 'en'
  weight: 1
  title: 'Eshwara Prasad Sridhar'
  
  params:
    description: 'Ph.D. Student in Industrial Engineering at UT Arlington'
    
  menu:
    main:
      - name: 'Home'
        url: '/'
        weight: 10
      - name: 'Publications'
        url: '/publications/'
        weight: 40
      - name: 'CV'
        url: '/resume.pdf'
        weight: 50
        params:
          external: true
