main:
  - name: 'Home'
    url: '/'
    weight: 10
  - name: 'Publications'
    url: '/#publications'
    weight: 40
  - name: 'CV'
    url: '/EshwaraPrasadSridhar_Resume_PhD.pdf'
    weight: 50
    params:
      external: true
